name: CI/CD Pipeline

on:
  push:
    branches:  [ master ] 

jobs:
  continuous-dp:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create envioroment file
        run: |
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF
          ls
          pwd -P

      - name: Create docker images
        run: docker build -t 321102677516.dkr.ecr.us-east-1.amazonaws.com/embarca-ecr:oxylabs-blablacar .

      - name: Upload docker into ECR
        run: docker push 321102677516.dkr.ecr.us-east-1.amazonaws.com/embarca-ecr:oxylabs-blablacar

      - name: Install serverless framework
        run: curl -o- -L https://slss.io/install | bash

      - name: Deploy to Lambda Function and API Gateway
        run: npx serverless deploy 
